### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Marty25** [Yasinaaa/VkApp#1]
Hello! I'm getting these errors after build:

Information:Gradle tasks [:app:assembleDebug]
D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\model\Response.java
Error:(12, 19) error: class Response is already defined in package ru.android.vkapp.model
Error:(9, 5) error: annotation type not applicable to this kind of declaration
D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java
Error:(118, 63) error: cannot find symbol variable response
Error:(129, 45) error: cannot find symbol variable response
Error:(138, 58) error: cannot find symbol variable response
Error:(142, 62) error: cannot find symbol variable response
Error:(163, 63) error: cannot find symbol variable response
Error:(164, 45) error: cannot find symbol variable response
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED
> Information:Total time: 1.026 secs
> Error:D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\model\Response.java:12: error: class Response is already defined in package ru.android.vkapp.model
>     public static class Response{
>                   ^
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\model\Response.java:9: error: annotation type not applicable to this kind of declaration
>     @SerializedName("response")
>     ^
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java:118: error: cannot find symbol
>                 Response.Response.Item[] posts = postsResponse.response.items;
>                                                               ^
>   symbol:   variable response
>   location: variable postsResponse of type Response
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java:129: error: cannot find symbol
>                 lastPostInfo = postsResponse.response.next_from;
>                                             ^
>   symbol:   variable response
>   location: variable postsResponse of type Response
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java:138: error: cannot find symbol
>         for(Response.Response.Group group : postsResponse.response.groups){
>                                                          ^
>   symbol:   variable response
>   location: variable postsResponse of type Response
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java:142: error: cannot find symbol
>         for(Response.Response.Profile profile : postsResponse.response.profiles){
>                                                              ^
>   symbol:   variable response
>   location: variable postsResponse of type Response
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java:163: error: cannot find symbol
>                 Response.Response.Item[] posts = postsResponse.response.items;
>                                                               ^
>   symbol:   variable response
>   location: variable postsResponse of type Response
> D:\Dev\VkApp-master-3\app\src\main\java\ru\android\vkapp\presenter\MainPresenter.java:164: error: cannot find symbol
>                 lastPostInfo = postsResponse.response.next_from;
>                                             ^
>   symbol:   variable response
>   location: variable postsResponse of type Response
> 8 errors
> FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Information:10 errors
Information:0 warnings
Information:See complete output in console

**Comment by Yasinaaa** [comment]
Marty, thank you for your attention) I solved that bug
